### ISSUE TITLE
Dica

### ISSUE THREAD

**Issue by imajoke** [Tur1st4/new-tab#1]
deixa a imagem adaptativa ao layout da tela(nao sei se vai entender mas é isso qualquer coisa pergunta no discord)
outra tbm coloca um random de imagens :) (se quiser)
outra tbm hehehe faz cada extensao dedicada a um tipo de "genero" anime, planetas, psicolodelicos, dark e etocetoras.

**Comment by Tur1st4** [comment]
> deixa a imagem adaptativa ao layout da tela(nao sei se vai entender mas é isso qualquer coisa pergunta no discord)
> outra tbm coloca um random de imagens :) (se quiser)
> outra tbm hehehe faz cada extensao dedicada a um tipo de "genero" anime, planetas, psicolodelicos, dark e etocetoras.

A Imagem adaptativa já foi adicionada;
Logo vou adicionar a opção para mudar a imagem;
 E não entendi muito bem a ultima das extensões, mas vou colocar os bookmarks para o user adicionar o que quiser, então vai ficar bem customizável.
